version: 2
jobs:
  full-build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn package source:jar javadoc:jar
  build-and-deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn package
      - run: mvn deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - full-build
      - build-and-deploy:
          requires:
            - full-build
          filters:
            branches:
              only:
                - master
                - snapshot
          context: snapshot-deploy
